[package]
name = "surgefx-allpass"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"

[dependencies.surge-constants]
path = "../surge-constants"

[dependencies.surge-math]
path = "../surge-math"

[dependencies.surge-lipol]
path = "../surge-lipol"

[dependencies.surge-quadrosc]
path = "../surge-quadrosc"

[dependencies.surge-samplerate]
path = "../surge-samplerate"

[dependencies.surge-macros]
path = "../surge-macros"

[dependencies.surge-types]
path = "../surge-types"

[dependencies.surge-traits]
path = "../surge-traits"

[dependencies]
enhanced_enum = "*"
getset = "*"
num-traits = "*"
paste = "*"
