[package]
name = "surgeosc-fm2"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"
vendor = "0.1.0"

[dependencies.surge-input]
path = "../surge-input"
vendor = "0.1.0"

[dependencies.surge-constants]
path = "../surge-constants"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-tables]
path = "../surge-tables"
vendor = "0.1.0"

[dependencies.surge-tuning]
path = "../surge-tuning"
vendor = "0.1.0"

[dependencies.surge-quadrosc]
path = "../surge-quadrosc"
vendor = "0.1.0"

[dependencies.surge-lag]
path = "../surge-lag"
vendor = "0.1.0"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies.surge-types]
path = "../surge-types"
vendor = "0.1.0"

[dependencies.surge-macros]
path = "../surge-macros"
vendor = "0.1.0"

[dependencies.surge-traits]
path = "../surge-traits"
vendor = "0.1.0"

[dependencies]
enhanced_enum = "*"
paste = "*"
