[package]
name = "surgeshaper-digi"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-filter]
path = "../surge-filter"

[dependencies.surge-math]
path = "../surge-math"
