[package]
name = "surgeshaper-asym"
version = "0.1.1-alpha.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-filter]
path = "../surge-filter"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-tables]
path = "../surge-tables"
vendor = "0.1.0"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies]
