[package]
description = "surge synthesizer -- obxd filter"
license = "GPL-3.0"
name = "surgefilter-obxd"
version = "0.1.1-alpha.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enhanced_enum = "*"
float-ord = "*"
derivative = "*"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies.surge-tuning]
path = "../surge-tuning"
vendor = "0.1.0"

[dependencies.surge-filter]
path = "../surge-filter"
vendor = "0.1.0"

[dependencies.surge-qfunit]
path = "../surge-qfunit"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-constants]
path = "../surge-constants"
vendor = "0.1.0"

[dependencies.surge-types]
path = "../surge-types"
vendor = "0.1.0"