[dependencies]
approx = "0.5.0"
approx_eq = "0.1.8"
atomic_float = "0.1.0"
bincode = "1.3.3"
bitflags = "1.3.2"
byteorder = "0.5.3"
derive_more = "0.99.16"
enhanced_enum = "0.2.2"
float-cmp = "0.9.0"
float-ord = "0.3.2"
getset = "0.1.1"
half = "1.8.2"
lazy_static = "1.4.0"
libc = "0.2.105"
ndarray = "0.15.3"
num = "0.4.0"
num-complex = "0.4.0"
num-traits = "0.2.14"
paste = "1.0.5"
rand = "0.8.4"
[package]
authors = [ "Adam Raisbeck <sense@i2pi.com>", "Alec DiAstra <alecdiastra@gmail.com>", "Alexandre Bique <bique.alexandre@gmail.com>", "Amy Furniss <http://github.com/amyfurniss>", "Brian Ginsburg <https://github.com/bgins>", "Cale Gibbard <cgibbard@gmail.com>", "Claes Johanson <claes@bitwig.com>", "Dave Palmer <itsmedavep@gmail.com>", "David Bata <https://github.com/tank-trax>", "David Carlier <devnexen@gmail.com>", "Erik-Jan Maalderink <fonkle@gmx.com>", "Esa Juhani Ruoho <esaruoho@gmail.com>", "Filipe Coelho <falktx@falktx.com>", "Hendrik van Boetzelaer <http://opuswerk.com>", "Jacky Ligon <http://jackyligon.com>", "Jani Frilander <http://github.com/janifr>", "Jarkko Sakkinen <jarkko.sakkinen@iki.fi>", "Jatin Chowdhury <jatin@ccrma.stanford.edu>", "Jean Pierre Cimalando <jp-dev@inbox.ru>", "Jeff Smith <whydoubt@gmail.com>", "Jeremy Sagan <info@sagantech.biz>", "Jon Spruyt <http://jonspru.yt>", "Keith Zantow <kzantow@gmail.com>", "Kjetil Matheussen <k.s.matheussen@notam02.no>", "Korridor <fabian.kempe@gmail.com>", "Luna Langton <https://github.com/selenologist>", "Mario Krušelj a.k.a. EvilDragon <http://github.com/mkruselj>", "Markku Tavasti <tavasti@iki.fi>", "Marty Lake <matthieu@talbot.audio>", "Matthias von Faber <http://github.com/mvf>", "Mikko Saarinki <https://github.com/kingston1>", "Nathan Kopp <nk.sg@nathankopp.com>", "Paul Walker <paul@pwjw.com>", "Rich Elmes <richie@juic3.com>", "Sebastian Schwarzhuber <https://github.com/cannero>", "The Emu (J Riley Hill) <http://jrileyhill.com>", "Vincent Zauhar <v.zauhar@bell.net>", "klebs <none>", "muhl <https://github.com/mynameismuhl>", "簡志瑋 <dppss92132@gmail.com>" ]
description = "surge synthesizer -- dsp math used in synthesis"
edition = "2018"
license = "GPL-3.0"
name = "surge-math"
version = "0.1.11-alpha.0"
