[package]
description = "surge synthesizer -- surge super oscillator (SSO)"
license = "GPL-3.0"
name = "surgeosc-super"
version = "0.1.2-alpha.0"
authors = [ 
    "Adam Raisbeck <sense@i2pi.com>",
    "Alec DiAstra <alecdiastra@gmail.com>",
    "Alexandre Bique <bique.alexandre@gmail.com>",
    "Amy Furniss <http://github.com/amyfurniss>",
    "Brian Ginsburg <https://github.com/bgins>",
    "Cale Gibbard <cgibbard@gmail.com>",
    "Claes Johanson <claes@bitwig.com>",
    "Dave Palmer <itsmedavep@gmail.com>",
    "David Bata <https://github.com/tank-trax>",
    "David Carlier <devnexen@gmail.com>",
    "Erik-Jan Maalderink <fonkle@gmx.com>",
    "Esa Juhani Ruoho <esaruoho@gmail.com>",
    "Filipe Coelho <falktx@falktx.com>",
    "Hendrik van Boetzelaer <http://opuswerk.com>",
    "Jacky Ligon <http://jackyligon.com>",
    "Jani Frilander <http://github.com/janifr>",
    "Jarkko Sakkinen <jarkko.sakkinen@iki.fi>",
    "Jatin Chowdhury <jatin@ccrma.stanford.edu>",
    "Jean Pierre Cimalando <jp-dev@inbox.ru>",
    "Jeff Smith <whydoubt@gmail.com>",
    "Jeremy Sagan <info@sagantech.biz>",
    "Jon Spruyt <http://jonspru.yt>",
    "Keith Zantow <kzantow@gmail.com>",
    "Kjetil Matheussen <k.s.matheussen@notam02.no>",
    "Korridor <fabian.kempe@gmail.com>",
    "Luna Langton <https://github.com/selenologist>",
    "Mario Krušelj a.k.a. EvilDragon <http://github.com/mkruselj>",
    "Markku Tavasti <tavasti@iki.fi>",
    "Marty Lake <matthieu@talbot.audio>",
    "Matthias von Faber <http://github.com/mvf>",
    "Mikko Saarinki <https://github.com/kingston1>",
    "Nathan Kopp <nk.sg@nathankopp.com>",
    "Paul Walker <paul@pwjw.com>",
    "Rich Elmes <richie@juic3.com>",
    "Sebastian Schwarzhuber <https://github.com/cannero>",
    "The Emu (J Riley Hill) <http://jrileyhill.com>",
    "Vincent Zauhar <v.zauhar@bell.net>",
    "klebs <none>",
    "muhl <https://github.com/mynameismuhl>",
    "簡志瑋 <dppss92132@gmail.com>",
    ]

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"
vendor = "0.1.0"

[dependencies.surge-constants]
path = "../surge-constants"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-blitter]
path = "../surge-blitter"
vendor = "0.1.0"

[dependencies.surge-lag]
path = "../surge-lag"
vendor = "0.1.0"

[dependencies.surge-lipol]
path = "../surge-lipol"
vendor = "0.1.0"

[dependencies.surge-tables]
path = "../surge-tables"
vendor = "0.1.0"

[dependencies.surge-tuning]
path = "../surge-tuning"
vendor = "0.1.0"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies.surge-traits]
path = "../surge-traits"
vendor = "0.1.0"

[dependencies.surge-types]
path = "../surge-types"
vendor = "0.1.0"

[dependencies.surge-macros]
path = "../surge-macros"
vendor = "0.1.0"

[dependencies]
enhanced_enum = "*"
paste = "*"
