[package]
name = "surgeosc-audioin"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"

[dependencies.surge-input]
path = "../surge-input"

[dependencies.surge-constants]
path = "../surge-constants"

[dependencies.surge-traits]
path = "../surge-traits"

[dependencies.surge-types]
path = "../surge-types"

[dependencies.surge-math]
path = "../surge-math"

[dependencies.surge-tables]
path = "../surge-tables"

[dependencies.surge-macros]
path = "../surge-macros"

[dependencies]
enhanced_enum = "*"
paste = "*"
