[package]
name = "surgefx-flanger"
version = "0.1.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"

[dependencies.surge-halfrate]
path = "../surge-halfrate"

[dependencies.surge-constants]
path = "../surge-constants"

[dependencies.surge-math]
path = "../surge-math"

[dependencies.surge-lipol]
path = "../surge-lipol"

[dependencies.surge-quadrosc]
path = "../surge-quadrosc"

[dependencies.surge-lag]
path = "../surge-lag"

[dependencies.surge-samplerate]
path = "../surge-samplerate"

[dependencies.surge-tuning]
path = "../surge-tuning"

[dependencies.surge-tables]
path = "../surge-tables"

[dependencies.surge-traits]
path = "../surge-traits"

[dependencies.surge-types]
path = "../surge-types"

[dependencies.surge-macros]
path = "../surge-macros"

[dependencies.surge-timeunit]
path = "../surge-timeunit"

[dependencies.surge-biquad]
path = "../surge-biquad"

[dependencies]
enhanced_enum = "*"
paste = "*"
