[package]
name = "surgeosc-window"
version = "0.1.1-alpha.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-param]
path = "../surge-param"
vendor = "0.1.0"

[dependencies.surge-constants]
path = "../surge-constants"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-blitter]
path = "../surge-blitter"
vendor = "0.1.0"

[dependencies.surge-lag]
path = "../surge-lag"
vendor = "0.1.0"

[dependencies.surge-lipol]
path = "../surge-lipol"
vendor = "0.1.0"

[dependencies.surge-tables]
path = "../surge-tables"
vendor = "0.1.0"

[dependencies.surge-tuning]
path = "../surge-tuning"
vendor = "0.1.0"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies.surge-wavetable]
path = "../surge-wavetable"
vendor = "0.1.0"

[dependencies.surge-traits]
path = "../surge-traits"
vendor = "0.1.0"

[dependencies.surge-types]
path = "../surge-types"
vendor = "0.1.0"

[dependencies.surge-macros]
path = "../surge-macros"
vendor = "0.1.0"

[dependencies]
enhanced_enum = "*"
num-traits = "*"
paste = "*"
ndarray = "*"
