[package]
description = "surge synthesizer -- ring modulator effect"
license = "GPL-3.0"
name = "surgefx-ringmod"
version = "0.1.1-alpha.0"
authors = ["klebs <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.surge-biquad]
path = "../surge-biquad"
vendor = "0.1.0"

[dependencies.surgeosc-sine]
path = "../surgeosc-sine"
vendor = "0.1.0"

[dependencies.surge-constants]
path = "../surge-constants"
vendor = "0.1.0"

[dependencies.surge-param]
path = "../surge-param"
vendor = "0.1.0"

[dependencies.surge-tables]
path = "../surge-tables"
vendor = "0.1.0"

[dependencies.surge-tuning]
path = "../surge-tuning"
vendor = "0.1.0"

[dependencies.surge-lipol]
path = "../surge-lipol"
vendor = "0.1.0"

[dependencies.surge-math]
path = "../surge-math"
vendor = "0.1.0"

[dependencies.surge-samplerate]
path = "../surge-samplerate"
vendor = "0.1.0"

[dependencies.surge-timeunit]
path = "../surge-timeunit"
vendor = "0.1.0"

[dependencies.surge-halfrate]
path = "../surge-halfrate"
vendor = "0.1.0"

[dependencies.surge-types]
path = "../surge-types"
vendor = "0.1.0"

[dependencies.surge-macros]
path = "../surge-macros"
vendor = "0.1.0"

[dependencies.surge-traits]
path = "../surge-traits"
vendor = "0.1.0"

[dependencies]
enhanced_enum = "*"
paste = "*"
float-ord = "*"